-- AnalysisApp shares the signal database with AcquisitionApp.
-- The full schema (signals table + views) lives in:
--   AcquisitionApp/schema/init.sql
-- Run that file once before starting either app.
